# Generated by Django 6.1 on 2026-08-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investigation',
            name='cv_file',
        ),
        migrations.AddField(
            model_name='investigation',
            name='cv_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
